//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../../../../lml2468/xclaw/core/control/wire/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as control$0 from "../../../../lml2468/xclaw/desktop/internal/control/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "xclaw:event": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = wire$0.Envelope.createFrom;

configure();
