// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BotResult is the provisioned bot's identity returned to the wizard.
 */
export class BotResult {
    "robotId": string;

    /**
     * bf_… — stored in the keychain, never config.json
     */
    "botToken": string;

    /** Creates a new BotResult instance. */
    constructor($$source: Partial<BotResult> = {}) {
        if (!("robotId" in $$source)) {
            this["robotId"] = "";
        }
        if (!("botToken" in $$source)) {
            this["botToken"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BotResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BotResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BotResult($$parsedSource as Partial<BotResult>);
    }
}
