// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ToolPolicy is the per-bot tool surface.
 *   - Default is the bot-level whitelist. nil → unset (driver resolves the
 *     binary's probed headless-safe set); a non-nil (incl. empty) slice is
 *     used verbatim (empty = no tools). NB: no omitempty on Default — an
 *     explicit empty list (muzzle) must survive a JSON round-trip distinct
 *     from absent. The parent Tools pointer is omitempty, so an unconfigured
 *     bot omits the whole block; once present, default serializes as [] vs
 *     a non-empty list vs null(unset).
 *   - Channels overrides Default per sessionKey (group = channelId; DM =
 *     "<spaceId>:<uid>" or bare uid — the same key the router derives). A
 *     present entry is used verbatim (incl. empty = muzzle that channel).
 * 
 * Unconfigured channels (and the desktop Console) fall through to the global
 * headless-safe set.
 */
export class ToolPolicy {
    "default": string[];
    "channels"?: { [_ in string]?: string[] };

    /** Creates a new ToolPolicy instance. */
    constructor($$source: Partial<ToolPolicy> = {}) {
        if (!("default" in $$source)) {
            this["default"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolPolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolPolicy {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("default" in $$parsedSource) {
            $$parsedSource["default"] = $$createField0_0($$parsedSource["default"]);
        }
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField1_0($$parsedSource["channels"]);
        }
        return new ToolPolicy($$parsedSource as Partial<ToolPolicy>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $$createType0);
