// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChannelToolsInfo is the chat panel's view of a conversation's tool override:
 * Configured=false → the channel uses the bot default (Tools is then ignored).
 */
export class ChannelToolsInfo {
    "configured": boolean;
    "tools": string[];

    /** Creates a new ChannelToolsInfo instance. */
    constructor($$source: Partial<ChannelToolsInfo> = {}) {
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelToolsInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelToolsInfo {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField1_0($$parsedSource["tools"]);
        }
        return new ChannelToolsInfo($$parsedSource as Partial<ChannelToolsInfo>);
    }
}

/**
 * OctoCliStatus is the per-bot octo-cli registration state surfaced to the
 * Octo-integration pane: registered iff ~/.octo-cli/config.json has an entry
 * for the bot's OCTO_BOT_ID. RobotID is included so the UI can show what we
 * looked up (and reveal mismatches between config and what's actually in env).
 */
export class OctoCliStatus {
    "registered": boolean;
    "robotId": string;

    /** Creates a new OctoCliStatus instance. */
    constructor($$source: Partial<OctoCliStatus> = {}) {
        if (!("registered" in $$source)) {
            this["registered"] = false;
        }
        if (!("robotId" in $$source)) {
            this["robotId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OctoCliStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): OctoCliStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OctoCliStatus($$parsedSource as Partial<OctoCliStatus>);
    }
}

/**
 * ToolsetInfo is the tool-picker view of the probed claude tool surface.
 * Probed is false when claude has not been probed yet (no binary / first run);
 * the picker then shows a "probing…" state. HeadlessSafe is the set the picker
 * offers (Available minus interactive tools).
 */
export class ToolsetInfo {
    "probed": boolean;
    "claudeVersion": string;
    "headlessSafe": string[];

    /** Creates a new ToolsetInfo instance. */
    constructor($$source: Partial<ToolsetInfo> = {}) {
        if (!("probed" in $$source)) {
            this["probed"] = false;
        }
        if (!("claudeVersion" in $$source)) {
            this["claudeVersion"] = "";
        }
        if (!("headlessSafe" in $$source)) {
            this["headlessSafe"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolsetInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolsetInfo {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headlessSafe" in $$parsedSource) {
            $$parsedSource["headlessSafe"] = $$createField2_0($$parsedSource["headlessSafe"]);
        }
        return new ToolsetInfo($$parsedSource as Partial<ToolsetInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
