// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OctoBuddyService is the Wails-bound bridge: it owns the octobuddy-daemon supervisor and the
 * control-bus client, exposes command + config methods to the frontend, and
 * forwards the daemon's envelope stream as Wails events.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../core/control/wire/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as configstore$0 from "./internal/configstore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as control$0 from "./internal/control/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as octoapi$0 from "./internal/octoapi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as octocli$0 from "./internal/octocli/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skills$0 from "./internal/skills/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workflows$0 from "./internal/workflows/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspace$0 from "./internal/workspace/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BotSkillCreate scaffolds a new per-bot skill bundle.
 */
export function BotSkillCreate(botID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(6569680, botID, name);
}

/**
 * BotSkillDelete removes one of the bot's skill bundles.
 */
export function BotSkillDelete(botID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1487718959, botID, name);
}

/**
 * BotSkillDeleteFile removes a file within one of the bot's skill bundles.
 */
export function BotSkillDeleteFile(botID: string, name: string, rel: string): $CancellablePromise<void> {
    return $Call.ByID(2790927073, botID, name, rel);
}

/**
 * BotSkillFiles lists files in one of the bot's skill bundles.
 */
export function BotSkillFiles(botID: string, name: string): $CancellablePromise<string[]> {
    return $Call.ByID(2467324339, botID, name).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BotSkillRead reads a file within one of the bot's skill bundles.
 */
export function BotSkillRead(botID: string, name: string, rel: string): $CancellablePromise<string> {
    return $Call.ByID(3756526264, botID, name, rel);
}

/**
 * BotSkillWrite writes a file within one of the bot's skill bundles.
 */
export function BotSkillWrite(botID: string, name: string, rel: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(188442547, botID, name, rel, content);
}

/**
 * BotSkillsList returns a bot's skill bundles.
 */
export function BotSkillsList(botID: string): $CancellablePromise<skills$0.SkillInfo[]> {
    return $Call.ByID(6714641, botID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * BotWorkflowCreate scaffolds a new per-bot workflow script.
 */
export function BotWorkflowCreate(botID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1139562354, botID, name);
}

/**
 * BotWorkflowDelete removes one of the bot's workflow scripts.
 */
export function BotWorkflowDelete(botID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2940089713, botID, name);
}

/**
 * BotWorkflowRead reads one of the bot's workflow scripts.
 */
export function BotWorkflowRead(botID: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3704072622, botID, name);
}

/**
 * BotWorkflowWrite writes one of the bot's workflow scripts.
 */
export function BotWorkflowWrite(botID: string, name: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(27652337, botID, name, content);
}

/**
 * BotWorkflowsList returns a bot's workflow scripts.
 */
export function BotWorkflowsList(botID: string): $CancellablePromise<workflows$0.Info[]> {
    return $Call.ByID(864764999, botID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * BotsList requests the bot roster.
 */
export function BotsList(): $CancellablePromise<void> {
    return $Call.ByID(2883740028);
}

/**
 * CronCreate schedules a task (owner-gated by the daemon).
 */
export function CronCreate(body: control$0.CronCreateBody): $CancellablePromise<void> {
    return $Call.ByID(764055326, body);
}

/**
 * CronDelete removes a scheduled task.
 */
export function CronDelete(botID: string, uid: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(1594311957, botID, uid, id);
}

/**
 * CronList lists a bot's scheduled tasks.
 */
export function CronList(botID: string): $CancellablePromise<void> {
    return $Call.ByID(2639987814, botID);
}

/**
 * CronUpdate mutates a scheduled task. The body's Enabled is a pointer so the
 * renderer's per-row enable/disable toggle can send an enabled-only update
 * (other fields zero) without re-validating the unchanged schedule on the
 * daemon — see core/cron Update's enabled-only fast path.
 */
export function CronUpdate(body: control$0.CronUpdateBody): $CancellablePromise<void> {
    return $Call.ByID(963819619, body);
}

/**
 * GroupsList enumerates the IM groups the bot is a member of, populated for
 * the scheduled-task target picker so the operator picks "this group" from
 * a dropdown instead of pasting a channelId. Synchronous (not fire-and-
 * forget over the control bus) because the renderer awaits it before
 * opening the create-task modal, same shape as OctoCliStatus.
 * 
 * Returns an empty list (and no error) when the bot has no groups; returns
 * an error when octo-cli is not installed / not authenticated for this bot
 * so the GUI can surface a meaningful "log in first" message rather than
 * silently showing "no groups available".
 */
export function GroupsList(botID: string): $CancellablePromise<octocli$0.Group[]> {
    return $Call.ByID(980157138, botID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Health requests a daemon health snapshot.
 */
export function Health(): $CancellablePromise<void> {
    return $Call.ByID(2597603676);
}

/**
 * History requests recent messages for a session (response arrives via EventStream).
 */
export function History(botID: string, sessionKey: string, limit: number): $CancellablePromise<void> {
    return $Call.ByID(4053444022, botID, sessionKey, limit);
}

/**
 * LoadConfig returns the editor view of every configured bot.
 */
export function LoadConfig(): $CancellablePromise<configstore$0.BotConfig[]> {
    return $Call.ByID(317365000).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * MemoryFile returns one session memory file's contents for inline preview,
 * bounded and traversal-safe.
 */
export function MemoryFile(botID: string, channelType: number, sessionKey: string, relPath: string): $CancellablePromise<workspace$0.FileContent> {
    return $Call.ByID(2248183679, botID, channelType, sessionKey, relPath).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * MemoryTree returns the file tree of a session's auto-memory directory
 * (read-only). Returns an empty tree when no memory has been written yet.
 */
export function MemoryTree(botID: string, channelType: number, sessionKey: string): $CancellablePromise<workspace$0.Node | null> {
    return $Call.ByID(1997019889, botID, channelType, sessionKey).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * OctoAddBot provisions a new bot on octo-server using the operator's User API
 * Key (uk_…), returning the bot's robot id + bf_ token. The wizard then folds
 * these into a BotConfig and calls SaveConfig — so the token reaches the
 * secret backend (never config.json) by the existing path. Self-service replacement
 * for the manual BotFather /newbot flow.
 */
export function OctoAddBot(apiURL: string, apiKey: string, name: string): $CancellablePromise<octoapi$0.BotResult> {
    return $Call.ByID(1338554973, apiURL, apiKey, name).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * OctoCliLogout clears the bot's disk profile. The stored bf_ token is
 * left alone — re-login can restore the profile from it.
 */
export function OctoCliLogout(botID: string): $CancellablePromise<void> {
    return $Call.ByID(1486321187, botID);
}

/**
 * OctoCliRelogin re-writes the disk profile for the bot from the stored
 * bf_ token. Used to repair a missing/stale profile from the Octo-integration
 * pane without forcing the operator to re-save the whole config.
 */
export function OctoCliRelogin(botID: string): $CancellablePromise<void> {
    return $Call.ByID(756879125, botID);
}

/**
 * OctoCliStatus reports whether the bot's octo-cli profile is registered.
 * Reads config.json directly; no octo-cli spawn needed (cheap for a UI poll).
 */
export function OctoCliStatus(botID: string): $CancellablePromise<$models.OctoCliStatus> {
    return $Call.ByID(3212560983, botID).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * Reset clears a session's resume mapping (start fresh).
 */
export function Reset(botID: string, uid: string): $CancellablePromise<void> {
    return $Call.ByID(1834369521, botID, uid);
}

/**
 * RestartCore restarts the daemon and reconnects (applies config changes). It
 * bumps the epoch first so any in-flight crash-reconnect loop bails instead of
 * racing this restart.
 */
export function RestartCore(): $CancellablePromise<void> {
    return $Call.ByID(2417701434);
}

/**
 * SaveConfig writes the bots back (config.json + SOUL/AGENTS + secret backend).
 * removedIDs is the explicit list of bot ids the editor deleted this session;
 * only those are pruned from disk (never an inferred set-difference). The caller
 * follows with RestartCore to apply.
 */
export function SaveConfig(bots: configstore$0.BotConfig[], removedIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(2359737065, bots, removedIDs);
}

/**
 * Send routes a DM message to a bot (botID may be empty for the default bot).
 */
export function Send(botID: string, uid: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(519019940, botID, uid, text);
}

/**
 * SessionsList requests all persisted sessions for a bot, newest first (response
 * arrives via EventStream as a sessions.list envelope).
 */
export function SessionsList(botID: string): $CancellablePromise<void> {
    return $Call.ByID(253189275, botID);
}

/**
 * UsageStats requests a bot's token usage over a range (since = Unix seconds at a
 * local-midnight bound; 0 = all time). The response arrives via EventStream as a
 * usage.stats envelope echoing `since`.
 */
export function UsageStats(botID: string, since: number): $CancellablePromise<void> {
    return $Call.ByID(440527224, botID, since);
}

/**
 * WorkspaceFile returns one workspace file's contents for inline preview
 * (utf8 text or base64 for images/binaries), bounded and traversal-safe.
 */
export function WorkspaceFile(botID: string, channelType: number, sessionKey: string, relPath: string): $CancellablePromise<workspace$0.FileContent> {
    return $Call.ByID(2447146625, botID, channelType, sessionKey, relPath).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * WorkspaceTree returns the file tree of a session's sandbox workspace
 * (read-only). Returns an empty tree when no turn has created the sandbox yet.
 */
export function WorkspaceTree(botID: string, channelType: number, sessionKey: string): $CancellablePromise<workspace$0.Node | null> {
    return $Call.ByID(710539635, botID, channelType, sessionKey).then(($result: any) => {
        return $$createType11($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = skills$0.SkillInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = workflows$0.Info.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = octocli$0.Group.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = configstore$0.BotConfig.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = workspace$0.FileContent.createFrom;
const $$createType10 = workspace$0.Node.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = octoapi$0.BotResult.createFrom;
const $$createType13 = $models.OctoCliStatus.createFrom;
