// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SkillInfo summarizes a skill for the list view.
 */
export class SkillInfo {
    "name": string;
    "description": string;
    "files": number;

    /** Creates a new SkillInfo instance. */
    constructor($$source: Partial<SkillInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillInfo($$parsedSource as Partial<SkillInfo>);
    }
}
