// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BotConfig is the flat view model the editor binds to. Tokens are populated
 * from the credential store on Load and routed back to it on Save.
 */
export class BotConfig {
    "id": string;
    "apiUrl": string;
    "model": string;
    "gatewayBaseUrl": string;
    "octoToken": string;
    "gatewayToken": string;
    "env": { [_ in string]?: string };
    "soul": string;
    "agents": string;

    /** Creates a new BotConfig instance. */
    constructor($$source: Partial<BotConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("apiUrl" in $$source)) {
            this["apiUrl"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("gatewayBaseUrl" in $$source)) {
            this["gatewayBaseUrl"] = "";
        }
        if (!("octoToken" in $$source)) {
            this["octoToken"] = "";
        }
        if (!("gatewayToken" in $$source)) {
            this["gatewayToken"] = "";
        }
        if (!("env" in $$source)) {
            this["env"] = {};
        }
        if (!("soul" in $$source)) {
            this["soul"] = "";
        }
        if (!("agents" in $$source)) {
            this["agents"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BotConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BotConfig {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField6_0($$parsedSource["env"]);
        }
        return new BotConfig($$parsedSource as Partial<BotConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
