// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * OctoCliStatus is the per-bot octo-cli registration state surfaced to the
 * Octo-integration pane: registered iff ~/.octo-cli/config.json has an entry
 * for the bot's OCTO_BOT_ID. RobotID is included so the UI can show what we
 * looked up (and reveal mismatches between config and what's actually in env).
 */
export class OctoCliStatus {
    "registered": boolean;
    "robotId": string;

    /** Creates a new OctoCliStatus instance. */
    constructor($$source: Partial<OctoCliStatus> = {}) {
        if (!("registered" in $$source)) {
            this["registered"] = false;
        }
        if (!("robotId" in $$source)) {
            this["robotId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OctoCliStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): OctoCliStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OctoCliStatus($$parsedSource as Partial<OctoCliStatus>);
    }
}
