// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * XClawService is the Wails-bound bridge: it owns the xclawd supervisor and the
 * control-bus client, exposes command + config methods to the frontend, and
 * forwards the daemon's envelope stream as Wails events.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../core/control/wire/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as configstore$0 from "./internal/configstore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as control$0 from "./internal/control/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skills$0 from "./internal/skills/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workflows$0 from "./internal/workflows/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspace$0 from "./internal/workspace/models.js";

/**
 * BotsList requests the bot roster.
 */
export function BotsList(): $CancellablePromise<void> {
    return $Call.ByID(2883740028);
}

/**
 * CronCreate schedules a task (owner-gated by the daemon).
 */
export function CronCreate(body: control$0.CronCreateBody): $CancellablePromise<void> {
    return $Call.ByID(764055326, body);
}

/**
 * CronDelete removes a scheduled task.
 */
export function CronDelete(botID: string, uid: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(1594311957, botID, uid, id);
}

/**
 * CronList lists a bot's scheduled tasks.
 */
export function CronList(botID: string): $CancellablePromise<void> {
    return $Call.ByID(2639987814, botID);
}

/**
 * Health requests a daemon health snapshot.
 */
export function Health(): $CancellablePromise<void> {
    return $Call.ByID(2597603676);
}

/**
 * History requests recent messages for a session (response arrives via EventStream).
 */
export function History(botID: string, sessionKey: string, limit: number): $CancellablePromise<void> {
    return $Call.ByID(4053444022, botID, sessionKey, limit);
}

/**
 * LoadConfig returns the editor view of every configured bot.
 */
export function LoadConfig(): $CancellablePromise<configstore$0.BotConfig[]> {
    return $Call.ByID(317365000).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Reset clears a session's resume mapping (start fresh).
 */
export function Reset(botID: string, uid: string): $CancellablePromise<void> {
    return $Call.ByID(1834369521, botID, uid);
}

/**
 * RestartCore restarts the daemon and reconnects (applies config changes). It
 * bumps the epoch first so any in-flight crash-reconnect loop bails instead of
 * racing this restart.
 */
export function RestartCore(): $CancellablePromise<void> {
    return $Call.ByID(2417701434);
}

/**
 * SaveConfig writes the bots back (config.json + SOUL/AGENTS + credential store).
 * removedIDs is the explicit list of bot ids the editor deleted this session;
 * only those are pruned from disk (never an inferred set-difference). The caller
 * follows with RestartCore to apply.
 */
export function SaveConfig(bots: configstore$0.BotConfig[], removedIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(2359737065, bots, removedIDs);
}

/**
 * Send routes a DM message to a bot (botID may be empty for the default bot).
 */
export function Send(botID: string, uid: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(519019940, botID, uid, text);
}

/**
 * SessionsList requests all persisted sessions for a bot, newest first (response
 * arrives via EventStream as a sessions.list envelope).
 */
export function SessionsList(botID: string): $CancellablePromise<void> {
    return $Call.ByID(253189275, botID);
}

/**
 * SkillCreate scaffolds a new skill (starter SKILL.md).
 */
export function SkillCreate(name: string): $CancellablePromise<void> {
    return $Call.ByID(1435339055, name);
}

/**
 * SkillDelete removes a skill bundle entirely.
 */
export function SkillDelete(name: string): $CancellablePromise<void> {
    return $Call.ByID(1356761844, name);
}

/**
 * SkillDeleteFile removes a file from a skill bundle.
 */
export function SkillDeleteFile(name: string, rel: string): $CancellablePromise<void> {
    return $Call.ByID(1212423266, name, rel);
}

/**
 * SkillFiles lists the relative file paths in a skill bundle.
 */
export function SkillFiles(name: string): $CancellablePromise<string[]> {
    return $Call.ByID(152150974, name).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SkillRead returns one file's contents from a skill bundle.
 */
export function SkillRead(name: string, rel: string): $CancellablePromise<string> {
    return $Call.ByID(3388404043, name, rel);
}

/**
 * SkillWrite creates/overwrites a file in a skill bundle.
 */
export function SkillWrite(name: string, rel: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2812285130, name, rel, content);
}

/**
 * SkillsList returns every skill in the global catalog.
 */
export function SkillsList(): $CancellablePromise<skills$0.SkillInfo[]> {
    return $Call.ByID(1013037060).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * UsageStats requests a bot's token usage over a range (since = Unix seconds at a
 * local-midnight bound; 0 = all time). The response arrives via EventStream as a
 * usage.stats envelope echoing `since`.
 */
export function UsageStats(botID: string, since: number): $CancellablePromise<void> {
    return $Call.ByID(440527224, botID, since);
}

/**
 * WorkflowCreate scaffolds a new workflow.
 */
export function WorkflowCreate(name: string): $CancellablePromise<void> {
    return $Call.ByID(867881607, name);
}

/**
 * WorkflowDelete removes a workflow.
 */
export function WorkflowDelete(name: string): $CancellablePromise<void> {
    return $Call.ByID(1678805052, name);
}

/**
 * WorkflowRead returns a workflow's script source.
 */
export function WorkflowRead(name: string): $CancellablePromise<string> {
    return $Call.ByID(555421379, name);
}

/**
 * WorkflowWrite creates/overwrites a workflow's script.
 */
export function WorkflowWrite(name: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2925081922, name, content);
}

/**
 * WorkflowsList returns every workflow in the global catalog.
 */
export function WorkflowsList(): $CancellablePromise<workflows$0.Info[]> {
    return $Call.ByID(2169000428).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * WorkspaceFile returns one workspace file's contents for inline preview
 * (utf8 text or base64 for images/binaries), bounded and traversal-safe.
 */
export function WorkspaceFile(botID: string, sessionKey: string, relPath: string): $CancellablePromise<workspace$0.FileContent> {
    return $Call.ByID(2447146625, botID, sessionKey, relPath).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * WorkspaceTree returns the file tree of a session's sandbox workspace
 * (read-only). Returns an empty tree when no turn has created the sandbox yet.
 */
export function WorkspaceTree(botID: string, sessionKey: string): $CancellablePromise<workspace$0.Node | null> {
    return $Call.ByID(710539635, botID, sessionKey).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = configstore$0.BotConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = skills$0.SkillInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = workflows$0.Info.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = workspace$0.FileContent.createFrom;
const $$createType8 = workspace$0.Node.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
