// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * XClawService is the Wails-bound bridge: it owns the xclawd supervisor and the
 * control-bus client, exposes command + config methods to the frontend, and
 * forwards the daemon's envelope stream as Wails events.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../core/control/wire/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as configstore$0 from "./internal/configstore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as control$0 from "./internal/control/models.js";

/**
 * BotsList requests the bot roster.
 */
export function BotsList(): $CancellablePromise<void> {
    return $Call.ByID(2883740028);
}

/**
 * CronCreate schedules a task (owner-gated by the daemon).
 */
export function CronCreate(body: control$0.CronCreateBody): $CancellablePromise<void> {
    return $Call.ByID(764055326, body);
}

/**
 * CronDelete removes a scheduled task.
 */
export function CronDelete(botID: string, uid: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(1594311957, botID, uid, id);
}

/**
 * CronList lists a bot's scheduled tasks.
 */
export function CronList(botID: string): $CancellablePromise<void> {
    return $Call.ByID(2639987814, botID);
}

/**
 * Health requests a daemon health snapshot.
 */
export function Health(): $CancellablePromise<void> {
    return $Call.ByID(2597603676);
}

/**
 * History requests recent messages for a session (response arrives via EventStream).
 */
export function History(botID: string, sessionKey: string, limit: number): $CancellablePromise<void> {
    return $Call.ByID(4053444022, botID, sessionKey, limit);
}

/**
 * LoadConfig returns the editor view of every configured bot.
 */
export function LoadConfig(): $CancellablePromise<configstore$0.BotConfig[]> {
    return $Call.ByID(317365000).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Reset clears a session's resume mapping (start fresh).
 */
export function Reset(botID: string, uid: string): $CancellablePromise<void> {
    return $Call.ByID(1834369521, botID, uid);
}

/**
 * RestartCore restarts the daemon and reconnects (applies config changes).
 */
export function RestartCore(): $CancellablePromise<void> {
    return $Call.ByID(2417701434);
}

/**
 * SaveConfig writes the bots back (config.json + SOUL/AGENTS + credential store).
 * The caller follows with RestartCore to apply.
 */
export function SaveConfig(bots: configstore$0.BotConfig[]): $CancellablePromise<void> {
    return $Call.ByID(2359737065, bots);
}

/**
 * Send routes a DM message to a bot (botID may be empty for the default bot).
 */
export function Send(botID: string, uid: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(519019940, botID, uid, text);
}

// Private type creation functions
const $$createType0 = configstore$0.BotConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
