// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../../core/config/models.js";

/**
 * BotConfig is the flat view model the editor binds to. Tokens are populated
 * from the secret backend on Load and routed back to it on Save.
 */
export class BotConfig {
    "id": string;
    "apiUrl": string;
    "model": string;
    "gatewayBaseUrl": string;
    "octoToken": string;
    "gatewayToken": string;
    "env": { [_ in string]?: string };
    "secretEnv": { [_ in string]?: boolean };
    "soul": string;
    "agents": string;

    /**
     * Cron mirrors agent.cron — surface-level toggle for the scheduled-task
     * manager. False (the default) means the bot's cron Manager is never
     * constructed, so the GUI's SchedulesPane shows an "启用并重启" banner
     * instead of an actionable task list. Round-tripped through Save so the
     * SchedulesPane toggle survives a config write.
     */
    "cron": boolean;

    /**
     * SystemPromptMode mirrors agent.systemPromptMode ("minimal" | "claude_code";
     * "" = minimal). Editable on the 基础信息 pane.
     */
    "systemPromptMode": string;

    /**
     * SettingSources mirrors agent.settingSources (subset of {user, project};
     * empty = ["user"]). Editable on the 基础信息 pane.
     */
    "settingSources": string[];

    /**
     * Tools mirrors agent.tools — bot-level default whitelist + per-channel
     * overrides. nil/absent = the driver's probed headless-safe default. The
     * bot-level default is edited on 基础信息; per-channel overrides are edited
     * in the chat window (E3) but round-tripped here so a 基础信息 save preserves
     * them.
     */
    "tools"?: config$0.ToolPolicy | null;

    /** Creates a new BotConfig instance. */
    constructor($$source: Partial<BotConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("apiUrl" in $$source)) {
            this["apiUrl"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("gatewayBaseUrl" in $$source)) {
            this["gatewayBaseUrl"] = "";
        }
        if (!("octoToken" in $$source)) {
            this["octoToken"] = "";
        }
        if (!("gatewayToken" in $$source)) {
            this["gatewayToken"] = "";
        }
        if (!("env" in $$source)) {
            this["env"] = {};
        }
        if (!("secretEnv" in $$source)) {
            this["secretEnv"] = {};
        }
        if (!("soul" in $$source)) {
            this["soul"] = "";
        }
        if (!("agents" in $$source)) {
            this["agents"] = "";
        }
        if (!("cron" in $$source)) {
            this["cron"] = false;
        }
        if (!("systemPromptMode" in $$source)) {
            this["systemPromptMode"] = "";
        }
        if (!("settingSources" in $$source)) {
            this["settingSources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BotConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BotConfig {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        const $$createField12_0 = $$createType2;
        const $$createField13_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField6_0($$parsedSource["env"]);
        }
        if ("secretEnv" in $$parsedSource) {
            $$parsedSource["secretEnv"] = $$createField7_0($$parsedSource["secretEnv"]);
        }
        if ("settingSources" in $$parsedSource) {
            $$parsedSource["settingSources"] = $$createField12_0($$parsedSource["settingSources"]);
        }
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField13_0($$parsedSource["tools"]);
        }
        return new BotConfig($$parsedSource as Partial<BotConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = config$0.ToolPolicy.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
