// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";

/**
 * CronCreateBody registers a scheduled task (proto: cron.create). Owner-gated on
 * the SERVER-resolved owner uid, not on any field here — the body uid is not an
 * authorization claim (it is forgeable; the agent reaches cron over an
 * agent-controlled CLI). The created task BINDS to the channel coords given
 * here: a channelId (group) targets that channel; omitting it targets the
 * owner's DM. The fired prompt always runs as the owner.
 */
export class CronCreateBody {
    "botId"?: string;

    /**
     * UID is accepted for proto compatibility but IGNORED for authorization and
     * for DM binding (the resolved owner is used for both). Deprecated.
     */
    "uid"?: string;

    /**
     * Schedule is a 5-field cron expr ("0 9 * * 1-5") or one-shot ISO datetime.
     */
    "schedule": string;

    /**
     * Prompt is the instruction injected when the task fires (≤ 2048 bytes).
     */
    "prompt": string;

    /**
     * Recurring, when set, overrides the default (cron→true, one-shot→false).
     */
    "recurring"?: boolean | null;

    /**
     * ChannelID + ChannelType bind a GROUP task. Omit (or type 1) for a DM task,
     * which binds to the resolved owner. ChannelType: 1 = DM, 2 = Group.
     */
    "channelId"?: string;
    "channelType"?: number;
    "fromName"?: string;

    /** Creates a new CronCreateBody instance. */
    constructor($$source: Partial<CronCreateBody> = {}) {
        if (!("schedule" in $$source)) {
            this["schedule"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CronCreateBody instance from a string or object.
     */
    static createFrom($$source: any = {}): CronCreateBody {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CronCreateBody($$parsedSource as Partial<CronCreateBody>);
    }
}

/**
 * Envelope is the single wire unit. body is left raw so each side decodes it
 * against the concrete command/event type named by `type`.
 */
export class Envelope {
    "v": number;
    "kind": Kind;

    /**
     * correlates command↔response
     */
    "id"?: string;

    /**
     * e.g. "session.send", "session.text"
     */
    "type": string;

    /**
     * unix seconds
     */
    "ts"?: number;

    /**
     * type-specific payload
     */
    "body"?: json$0.RawMessage;

    /** Creates a new Envelope instance. */
    constructor($$source: Partial<Envelope> = {}) {
        if (!("v" in $$source)) {
            this["v"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = Kind.$zero;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Envelope instance from a string or object.
     */
    static createFrom($$source: any = {}): Envelope {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Envelope($$parsedSource as Partial<Envelope>);
    }
}

/**
 * Kind discriminates the three envelope categories.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * client → server
     */
    KindCommand = "command",

    /**
     * server → client, correlated by id
     */
    KindResponse = "response",

    /**
     * server → client, unsolicited
     */
    KindEvent = "event",
};
