// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../../../core/control/wire/models.js";

/**
 * Re-export the wire vocabulary so callers depend on this package, not the
 * daemon's, for the contract surface they use.
 */
export const CronCreateBody = wire$0.CronCreateBody;

/**
 * Re-export the wire vocabulary so callers depend on this package, not the
 * daemon's, for the contract surface they use.
 */
export type CronCreateBody = wire$0.CronCreateBody;

/**
 * Re-export the wire vocabulary so callers depend on this package, not the
 * daemon's, for the contract surface they use.
 */
export const Envelope = wire$0.Envelope;

/**
 * Re-export the wire vocabulary so callers depend on this package, not the
 * daemon's, for the contract surface they use.
 */
export type Envelope = wire$0.Envelope;
