// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileContent is one file's body for inline preview. Content is UTF-8 text when
 * Encoding is "utf8", or base64-encoded bytes when "base64" (binary/images).
 */
export class FileContent {
    "path": string;
    "content": string;

    /**
     * "utf8" | "base64"
     */
    "encoding": string;
    "mime": string;
    "truncated": boolean;
    "size": number;

    /** Creates a new FileContent instance. */
    constructor($$source: Partial<FileContent> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }
        if (!("mime" in $$source)) {
            this["mime"] = "";
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileContent instance from a string or object.
     */
    static createFrom($$source: any = {}): FileContent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileContent($$parsedSource as Partial<FileContent>);
    }
}

/**
 * Node is a file or directory in the workspace tree. Path is relative to the
 * workspace root, forward-slashed; the root node has Path "". Children is nil for
 * files and for directories whose contents are deliberately not expanded (.claude
 * and anything past the depth cap).
 */
export class Node {
    "name": string;
    "path": string;
    "isDir": boolean;
    "children": (Node | null)[];

    /** Creates a new Node instance. */
    constructor($$source: Partial<Node> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Node instance from a string or object.
     */
    static createFrom($$source: any = {}): Node {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField3_0($$parsedSource["children"]);
        }
        return new Node($$parsedSource as Partial<Node>);
    }
}

// Private type creation functions
const $$createType0 = Node.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
